# Generated by Django 2.2.6 on 2019-10-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Login',
        ),
    ]
