# Generated by Django 2.2.6 on 2019-10-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20191017_2056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Register',
        ),
    ]
