# Generated by Django 2.2.6 on 2019-10-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20191018_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='confirm_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='confirm_password',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
